# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=128, verbose_name='official name')),
                ('slug', models.SlugField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('code',),
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='code INSEE')),
                ('name', models.CharField(max_length=128, verbose_name='official name')),
                ('slug', models.SlugField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Region2016',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='code INSEE')),
                ('name', models.CharField(max_length=128, verbose_name='official name')),
                ('slug', models.SlugField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'french_zones_region_2016',
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.AddField(
            model_name='region',
            name='region_2016',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='french_zones.Region2016'),
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='french_zones.Region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='department',
            name='region_2016',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='french_zones.Region2016'),
        ),
    ]
